### ISSUE TITLE
Error during compile Alsa-lib in Morty branch

### ISSUE THREAD

**Issue by ska** [tq-systems/meta-tq#2]
Hello all, 
I'm trying to compile a new qt5 image with Yocto (branch Morty) using the meta-qt layer. During the compilation of alsa-lib, the building system shows me this error:

`ERROR: alsa-lib-1.1.2-r0 do_compile: Function failed: do_compile (log file is located at /yocto/Morty_2.2/build_tqma6q/tmp/work/${MACHINE_SOCARCH}-poky-linux-gnueabi/alsa-lib/1.1.2-r0/temp/log.do_compile.15616)

ERROR: Logfile of failure stored in: /yocto/Morty_2.2/build_tqma6q/tmp/work/${MACHINE_SOCARCH}-poky-linux-gnueabi/alsa-lib/1.1.2-r0/temp/log.do_compile.15616
Log data follows:
| DEBUG: SITE files ['endian-little', 'bit-32', 'arm-common', 'arm-32', 'common-linux', 'common-glibc', 'arm-linux', 'arm-linux-gnueabi', 'common']
| DEBUG: Executing shell function do_compile
| NOTE: make -j 6
| make: *** No targets specified and no makefile found.  Stop.
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /yocto/Morty_2.2/build_tqma6q/tmp/work/${MACHINE_SOCARCH}-poky-linux-gnueabi/alsa-lib/1.1.2-r0/temp/log.do_compile.15616)
ERROR: Task (/yocto/Morty_2.2/sources/poky-morty/meta/recipes-multimedia/alsa/alsa-lib_1.1.2.bb:do_compile) failed with exit code '1'
`

Usually the MACHINE_SOCARCH are defined in meta-freescale, I've added the definition like below:

`git diff
diff --git a/conf/machine/tqma6q-mba6x.conf b/conf/machine/tqma6q-mba6x.conf
index e30946c..bdb2f71 100644
--- a/conf/machine/tqma6q-mba6x.conf
+++ b/conf/machine/tqma6q-mba6x.conf
@@ -43,3 +43,4 @@ UBOOT_CONFIG[spinor] = "tqma6q_mba6_spi_defconfig"
 
 WKS_FILE ?= "tqma6q-sdimg.wks"
 
+MACHINE_SOCARCH_mx6q = "tqma6q_mba6x"
`
Now all seems works good, maybe can be useful for your systems.

Best regards
Luigi

**Comment by tq-niebelm** [comment]
Hello,

thanks for pointing this out. Is this fixed when using the changes pushed today for meta-tq? We do now

include conf/machine/include/imx-base.inc

at the end of conf/machine/include/tqma6x.inc, which allows us to make use of features / recipes from meta-freescale if configured in bblayers.conf

Best Regards

Markus

**Comment by tq-niebelm** [comment]
Release is really outdated, should be fixed long timew ago
