### ISSUE TITLE
The machine defintions are not generic enought

### ISSUE THREAD

**Issue by AlbanBedel** [tq-systems/meta-tq#3]
The machine definitions and include for the COMs are setting many things not strictly related to the hardware support like IMAGE_FSTYPE or DISTRO_FEATURES. This make it difficult to create other machine definitions that don't impact the distro related settings and easily integrate with another distro.

Ideally the machine definitions should strictly limit themself to low level settings such as kernel and bootloader providers, but it is especially important for the COM include to only contain the bare minimum to allow using them when creating new machine definitions.

**Comment by kgraefe** [comment]
I ended up copying the include file into my own layer in order to modify IMAGE_FSTYPES and IMAGE_INSTALL.

That is not how it should work.

**Comment by tq-niebelm** [comment]
Sorry for late reply. We are aware of this. It shall definitely be fixed.

**Comment by tq-niebelm** [comment]
This should be fixed in hardknott branch
