### ISSUE TITLE
Dunfell support

### ISSUE THREAD

**Issue by kgraefe** [tq-systems/meta-tq#4]
All of the Yocto versions supported by this layer went out of official support: https://wiki.yoctoproject.org/wiki/Releases

Support for at least Yocto 3.1 Dunfell would be nice as this is an LTS version.

**Comment by tq-niebelm** [comment]
We offer hardknott as of today, although not all SOM are thoroughly tested yet and plan to support kirkstone as next LTS. Is dunfell still a hard requirement?

**Comment by kgraefe** [comment]
It just makes sense for us to use LTS versions in our projects as those are way easier to maintain. Hardknott is only supported until March 2022.

However, it has never been a hard requirement in the specific project I had in mind and the timeframe to update is gone by now anyway.

**Comment by kgraefe** [comment]
Adding Kirkstone LTS support resolves this issue.
