### ISSUE TITLE
Can't Enable CAAM on TQMLS1043A

### ISSUE THREAD

**Issue by mobyrktr** [tq-systems/meta-tq#5]
Hi,
I'm trying to use SEC interface of TQMLS1043A to use with OpenSSL. I did the kernel configuration according to [this page](https://docs.nxp.com/bundle/GUID-9160E9B1-ADBC-4313-9837-773DA05262FB/page/GUID-5296A777-C437-4E2F-8120-B643C228EE94.html#GUID-5296A777-C437-4E2F-8120-B643C228EE94). After that, in /lib/modules/${uname -r}/modules.builtin I see these modules:

```
kernel/drivers/crypto/caam/error.ko
kernel/drivers/crypto/caam/caam.ko
kernel/drivers/crypto/caam/caam_jr.ko
kernel/drivers/crypto/caam/caamalg_desc.ko
kernel/drivers/crypto/caam/caamhash_desc.ko
```

But I can't see the encryption algorithms provided by caam in /proc/crypto

Current kernel config:
```shell
root@tqmls1043a-mbls10xxa:~# zcat /proc/config.gz | grep CAAM
CONFIG_CRYPTO_DEV_FSL_CAAM_COMMON=y
CONFIG_CRYPTO_DEV_FSL_CAAM_CRYPTO_API_DESC=y
CONFIG_CRYPTO_DEV_FSL_CAAM_AHASH_API_DESC=y
CONFIG_CRYPTO_DEV_FSL_CAAM=y
# CONFIG_CRYPTO_DEV_FSL_CAAM_DEBUG is not set
CONFIG_CRYPTO_DEV_FSL_CAAM_JR=y
CONFIG_CRYPTO_DEV_FSL_CAAM_RINGSIZE=9
# CONFIG_CRYPTO_DEV_FSL_CAAM_INTC is not set
CONFIG_CRYPTO_DEV_FSL_CAAM_CRYPTO_API=y
CONFIG_CRYPTO_DEV_FSL_CAAM_CRYPTO_API_QI=y
CONFIG_CRYPTO_DEV_FSL_CAAM_AHASH_API=y
CONFIG_CRYPTO_DEV_FSL_CAAM_PKC_API=y
CONFIG_CRYPTO_DEV_FSL_CAAM_RNG_API=y
CONFIG_CRYPTO_DEV_FSL_DPAA2_CAAM=y
```

**Comment by tq-liedmann** [comment]
Hello, 
please contact us via the following email address:
support@tq-group.com
