### ISSUE TITLE
Plans for Scarthgap

### ISSUE THREAD

**Issue by jonte** [tq-systems/meta-tq#7]
Hi!

I'm working on a platform based on the tqma6ulx. We're currently using kirkstone. I see that you've begun work on the scarthgap-next branch. Do you have a planned release date for this work? Will the scarthgap release of meta-tq include support for the tqma6ulx?

Thanks & BR,
Jonatan

**Comment by tq-niebelm** [comment]
Hello Jonathan,

we're in the test phase for our first scarthgap release. Allthough this release will be focused on i.MX8 / i.MX93 with vendor kernel, the machines for TQMa6ULx[L] and TQMa6ULL[L] can be used. There are no substantial changes expected for the first release compared to the current scarthgap-next branch. So feel free  to use the current state for testing. We plan this release within the next two weeks.

We plan to upgrade from mainline kernel 6.1.y to 6.6.y for the mentioned machines until end of Q4 within our development for scarthgap. Up to this point changes made in kirkstone for 6.1.y will propagated to scarthgap.

Best regards

Markus

**Comment by jonte** [comment]
Sounds good, thank you for sharing the plans Markus.

My questions are answered, so I will close this ticket.
